# Generated by Django 3.2.4 on 2021-08-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membership_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.CharField(choices=[('free_trial', 'F'), ('member', 'M'), ('not_member', 'N')], max_length=10),
        ),
    ]
