# Generated by Django 3.2.4 on 2021-08-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_trackedrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='on_free_tail',
            new_name='on_free_trail',
        ),
    ]
