# Generated by Django 3.2.4 on 2021-08-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_on_free_tail_user_on_free_trail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='on_free_trail',
            new_name='on_free_trial',
        ),
    ]
